## Preparación inicial del dataset

Antes de iniciar el análisis de las variables, se realizó una serie de pasos preliminares con el objetivo de asegurar que el conjunto de datos estuviera correctamente cargado, accesible y en condiciones adecuadas para su análisis posterior.

### Obtención del dataset

El dataset utilizado fue obtenido desde la plataforma Kaggle, específicamente desde el conjunto **“Global Workplace Stress and Mental Health Survey”**. Para ello, se utilizó la API oficial de Kaggle dentro del entorno Google Colab.  
Este procedimiento permite que cualquier persona que ejecute el notebook pueda descargar los datos directamente desde la fuente original, garantizando reproducibilidad y transparencia en el proceso.

### Configuración del entorno

Para acceder a Kaggle desde Colab, fue necesario:

- Instalar la librería `kaggle`.
- Cargar el archivo de credenciales (`kaggle.json`) proporcionado por la plataforma.
- Ubicar dicho archivo en la ruta correcta del entorno y asignar los permisos necesarios.

Una vez configurado el entorno, se verificó que la conexión con Kaggle funcionara correctamente listando datasets y descargando el archivo correspondiente.

### Carga y verificación del archivo

Tras la descarga, el archivo CSV fue cargado en un DataFrame de pandas. Se realizaron comprobaciones básicas para asegurar que:

- El archivo se cargó correctamente.
- El número de filas y columnas coincidía con lo esperado.
- No existían problemas evidentes en la estructura del dataset.

### Inspección inicial de los datos

Como primer acercamiento al contenido del dataset, se revisaron:

- Las primeras filas del DataFrame.
- Los tipos de variables (categóricas y numéricas).
- La cantidad total de filas y columnas.

Esta inspección inicial permitió confirmar que los datos estaban completos, bien estructurados y listos para pasar a las siguientes etapas de limpieza, validación y descripción de variables.

A partir de este punto, el análisis se enfoca en comprender y describir las variables que componen el dataset.

In [ ]:
!pip -q install kaggle

In [ ]:
#Este bloque de código ejecuta dos comandos de shell
#!pwd: Este comando significa "Imprimir directorio de trabajo". Muestra la ruta absoluta del directorio de trabajo actual en su entorno Colab. En este caso, se generó /content, lo que indica que se encuentra en el directorio de contenido predeterminado.
#!ls -la: Este comando lista el contenido del directorio actual. Las opciones son:
#-l: Usa un formato de lista larga, que muestra información detallada como permisos, propietario, grupo, tamaño y fecha de modificación.
#-a: Lista todas las entradas, incluidos los archivos ocultos (aquellos que empiezan por un punto .).
#En conjunto, estos comandos indican dónde se encuentra en el sistema de archivos y qué archivos y directorios se encuentran en esa ubicación, junto con sus atributos detallados.

!pwd
!ls -la

/content
total 13564
drwxr-xr-x 1 root root     4096 Jan 31 15:32 .
drwxr-xr-x 1 root root     4096 Jan 31 15:24 ..
drwxr-xr-x 4 root root     4096 Jan 16 14:24 .config
-rw-r--r-- 1 root root  2600337 Jan 31 15:32 dataset_numeric.csv
drwx------ 5 root root     4096 Jan 31 15:27 drive
-rw-r--r-- 1 root root       70 Jan 31 15:31 kaggle.json
drwxr-xr-x 1 root root     4096 Jan 16 14:24 sample_data
-rw-r--r-- 1 root root 11260727 Jan 31 15:32 stress_data.csv

In [ ]:
#Este código, !find / -maxdepth 3 -name "kaggle*.json" 2>/dev/null, es un comando de shell que busca archivos. A continuación, se detalla:

#!find: El signo ! indica que se trata de un comando de shell que se ejecutará. find es una utilidad de línea de comandos para localizar archivos y directorios.
#/: Especifica el directorio de inicio de la búsqueda, que es el directorio raíz del sistema de archivos. Por lo tanto, se buscará en todo el sistema de archivos.
#-maxdepth 3: Esta opción limita la búsqueda a un máximo de 3 directorios. Significa que buscará en el directorio raíz, sus subdirectorios inmediatos y los subdirectorios de estos, pero no más allá.
#-name "kaggle*.json": Este es el criterio de búsqueda. Busca archivos cuyos nombres coincidan con el patrón "kaggle*.json". El * es un comodín que coincide con cualquier secuencia de caracteres, por lo que encontrará archivos como kaggle.json, kaggle_credentials.json, etc.
#2>/dev/null: Esta parte gestiona los mensajes de error. 2 se refiere al flujo de error estándar, y /dev/null es un dispositivo especial que descarta todos los datos escritos en él. Por lo tanto, cualquier mensaje de error generado por el comando find (por ejemplo, errores de permiso denegado en ciertos directorios) se suprimirá y no se mostrará en la salida.

!find / -maxdepth 3 -name "kaggle*.json" 2>/dev/null

/content/kaggle.json

In [ ]:
#Este bloque de código configura nuestras credenciales de la API de Kaggle en el entorno de Colab.
!mkdir -p /root/.config/kaggle #!mkdir: Este es un comando de shell para crear un directorio.-p: Esta opción le indica a mkdir que cree directorios principales según sea necesario. Si /root/.config no existe, lo creará junto con /root/.config/kaggle. /root/.config/kaggle: Esta es la ubicación estándar donde el cliente de la API de Kaggle espera encontrar tus credenciales de autenticación.
!cp /content/kaggle.json /root/.config/kaggle/kaggle.json #Este es un comando de shell para copiar archivos./content/kaggle.json: Esta es la ruta de origen de tu archivo de clave de la API de Kaggle, que probablemente se descargó en el directorio /content. /root/.config/kaggle/kaggle.json: Esta es la ruta de destino donde se debe colocar el archivo kaggle.json para que la API de Kaggle lo encuentre.
!chmod 600 /root/.config/kaggle/kaggle.json #Este es un comando de shell para cambiar los permisos de los archivos.600: Esta es una representación numérica de los permisos. Significa:6: Permisos de lectura y escritura para el propietario del archivo.0: Sin permisos para el grupo.0: Sin permisos para otros.Este comando es crucial para la seguridad. Garantiza que solo el propietario del archivo (en este caso, el usuario root del entorno de Colab) pueda leer y escribir en tu clave de API de Kaggle, lo que impide que otros usuarios o procesos accedan a tus credenciales.
!ls -la /root/.config/kaggle #!ls: Este es un comando de shell para listar el contenido del directorio. -l: Muestra la lista en formato largo, con detalles como los permisos de archivo, el propietario, el tamaño y la fecha de modificación.-a: Incluye archivos ocultos (aquellos que empiezan por un punto)./root/.config/kaggle: Especifica el directorio que se listará.Este comando se utiliza para verificar que el archivo kaggle.json se copió correctamente y que sus permisos están configurados como se esperaba.

total 12
drwxr-xr-x 2 root root 4096 Jan 31 15:31 .
drwxr-xr-x 1 root root 4096 Jan 31 15:27 ..
-rw------- 1 root root   70 Jan 31 15:38 kaggle.json

In [ ]:
!kaggle datasets list -s global-workplace-stress-and-mental-health-survey | head
#Este bloque de código utiliza la interfaz de línea de comandos (CLI) de Kaggle para buscar y mostrar información sobre conjuntos de datos.
#!kaggle datasets list: Este es un comando de la CLI de Kaggle que se utiliza para listar los conjuntos de datos disponibles en Kaggle.
#-s global-workplace-stress-and-mental-health-survey: El indicador -s se utiliza para buscar conjuntos de datos. La cadena que le sigue, global-workplace-stress-and-mental-health-survey, es la consulta de búsqueda.
#|head: El símbolo de barra vertical | envía la salida del comando kaggle como entrada al comando head. Por defecto, head muestra solo las primeras 10 líneas de su entrada. Esto es útil para obtener una vista previa rápida de los resultados de la búsqueda sin sobrecargar la salida.

ref                                                                 title                                                   size  lastUpdated                 downloadCount  voteCount  usabilityRating
------------------------------------------------------------------  ------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
mahdimashayekhi/mental-health                                       Mental Health                                         137847  2025-05-07 08:53:42.807000           5509         46  1.0
dhrubangtalukdar/global-mental-health-and-lifestyle-survey-dataset  Global Mental Health & Lifestyle Survey Dataset       411878  2026-01-29 01:39:38.597000            432         27  1.0
mutindafestus/global-workplace-stress-and-mental-health-survey      🌍 Global Workplace Stress & Mental Health Survey      932411  2025-10-22 15:07:17.317000             92          0  0.88235295
fesnicresearch/stress                                               stress                                                932411  2025-11-26 20:13:33.840000             12          0  0.4117647

In [ ]:
!kaggle datasets download -d mutindafestus/global-workplace-stress-and-mental-health-survey -p /content --unzip
!ls -la /content | head -80

#Este bloque de código primero descarga un conjunto de datos de Kaggle y luego lista los archivos en el directorio donde se descargó. A continuación, se detalla:
#!kaggle datasets download -d mutindafestus/global-workplace-stress-and-mental-health-survey -p /content --unzip:
#!kaggle datasets download: Este es un comando de la CLI de Kaggle para descargar un conjunto de datos.
#-d mutindafestus/global-workplace-stress-and-mental-health-survey: El indicador -d especifica el identificador del conjunto de datos que se descargará.
#-p /content: El indicador -p especifica la ruta donde se debe descargar el conjunto de datos. En este caso, es el directorio /content.
#--unzip: Esta opción descomprime automáticamente el archivo descargado (si es un archivo .zip) una vez completada la descarga.
#!ls -la /content | head -80:
#!ls -la /content: Este comando lista el contenido del directorio /content en formato largo (-l), incluyendo los archivos ocultos (-a).
#| head -80: El símbolo de barra vertical | envía la salida del comando ls al comando head. Head -80 muestra solo las primeras 80 líneas de esa salida. Esto es útil para inspeccionar rápidamente los archivos descargados y descomprimidos sin tener que desplazarse por una lista muy larga.

Dataset URL: https://www.kaggle.com/datasets/mutindafestus/global-workplace-stress-and-mental-health-survey
License(s): MIT
Downloading global-workplace-stress-and-mental-health-survey.zip to /content
  0% 0.00/911k [00:00<?, ?B/s]
100% 911k/911k [00:00<00:00, 1.29GB/s]
total 13564
drwxr-xr-x 1 root root     4096 Jan 31 15:38 .
drwxr-xr-x 1 root root     4096 Jan 31 15:24 ..
drwxr-xr-x 4 root root     4096 Jan 16 14:24 .config
-rw-r--r-- 1 root root  2600337 Jan 31 15:32 dataset_numeric.csv
drwx------ 5 root root     4096 Jan 31 15:27 drive
-rw-r--r-- 1 root root       70 Jan 31 15:31 kaggle.json
drwxr-xr-x 1 root root     4096 Jan 16 14:24 sample_data
-rw-r--r-- 1 root root 11260727 Jan 31 15:38 stress_data.csv

In [ ]:
import glob, pandas as pd
csvs = glob.glob("/content/*.csv")
csvs
#Este bloque de código está diseñado para encontrar todos los archivos CSV dentro del directorio /content y almacenar sus rutas. Veamos el proceso:
#import glob, pandas as pd: Esta línea importa dos bibliotecas de Python:
#glob: Este módulo encuentra todas las rutas que coinciden con un patrón específico según las reglas utilizadas por el shell de Unix. Es muy útil para encontrar archivos con ciertas extensiones o nombres en un directorio.
#pandas as pd: Importa la biblioteca pandas, una potente herramienta para la manipulación y el análisis de datos, a menudo utilizada para trabajar con DataFrames. Su alias es PD para mayor comodidad.
#csvs = glob.glob("/content/*.csv"): Esta línea utiliza la función glob.glob() para buscar todos los archivos que terminan en .csv dentro del directorio /content/. El * actúa como comodín, coincidiendo con cualquier carácter anterior a .csv. La lista de rutas a estos archivos CSV encontrados se almacena en una variable llamada csvs.
#csvs: Esta última línea simplemente muestra el contenido de la lista csvs, que le mostrará las rutas completas de todos los archivos CSV que se encuentran en /content/.

['/content/stress_data.csv', '/content/dataset_numeric.csv']

In [ ]:
!kaggle datasets download -d mutindafestus/global-workplace-stress-and-mental-health-survey -p /content --unzip
df = pd.read_csv("/content/stress_data.csv")
df.head()
#Este bloque de código primero descarga un conjunto de datos de Kaggle, luego lee el archivo CSV descargado en un DataFrame de Pandas y, finalmente, muestra las primeras filas de dicho DataFrame. A continuación, se ofrece una explicación detallada:
#!kaggle datasets download -d mutindafestus/global-workplace-stress-and-mental-health-survey -p /content --unzip:
#!kaggle datasets download: Este es un comando de la interfaz de línea de comandos (CLI) de Kaggle que se utiliza para descargar conjuntos de datos.
#-d mutindafestus/global-workplace-stress-and-mental-health-survey: El indicador -d especifica el identificador único del conjunto de datos que se descargará. En este caso, se trata del conjunto de datos "Encuesta Global de Estrés Laboral y Salud Mental".
#-p /content: El indicador -p indica la ruta de destino donde se debe guardar el conjunto de datos. En este caso, se guarda en el directorio /content de su entorno de Colab. --unzip: Esta opción extrae automáticamente el contenido del archivo .zip descargado tras guardarlo, lo que permite acceder directamente a los archivos CSV.
#df = pd.read_csv("/content/stress_data.csv"):
#pd.read_csv(): Esta función de Pandas se utiliza para leer datos de un archivo CSV en un DataFrame.
#"/content/stress_data.csv": Esta es la ruta al archivo CSV que se descargó y descomprimió en el paso anterior. La función lee los datos de este archivo y crea un DataFrame, que se asigna a la variable df.
#df.head():
#.head(): Este método de Pandas para DataFrame devuelve las primeras 5 filas del DataFrame por defecto. Es muy útil para inspeccionar rápidamente la estructura y el contenido de los datos después de cargarlos, para garantizar que se hayan cargado correctamente.

Dataset URL: https://www.kaggle.com/datasets/mutindafestus/global-workplace-stress-and-mental-health-survey
License(s): MIT
Downloading global-workplace-stress-and-mental-health-survey.zip to /content
  0% 0.00/911k [00:00<?, ?B/s]
100% 911k/911k [00:00<00:00, 1.24GB/s]

,Age,Gender,Industry,JobRole,Region,WorkLocation,AccessMH,wp1,wp2,wp3,...,EE3,EE4,EE5,EE6,EE7,WB1,WB2,WB3,WB4,WB5
0,26-35,Female,Consulting,Marketing,Africa,Remote,Yes,Sometimes,Often,Very often,...,Every day,A few times per year,Once a week,Every day,Every day,Most of the time,Less than half of the time,All of the time,Most of the time,Most of the time
1,56+,Prefer not to say,Education,Software Engineer,South America,Onsite,No,Sometimes,Never,Sometimes,...,Every day,Every day,A few times per week,Once a week,A few times per week,Most of the time,Most of the time,More than half of the time,More than half of the time,Most of the time
2,18-25,Female,Finance,HR,Asia,Onsite,No,Often,Often,Sometimes,...,Never,Once a week,Never,A few times per month,Never,More than half of the time,Some of the time,At no time,Less than half of the time,Some of the time
3,36-45,Male,Healthcare,Designer,Africa,Remote,Yes,Sometimes,Never,Sometimes,...,Once a week,A few times per week,Once a week,Once a week,Every day,More than half of the time,Less than half of the time,Most of the time,More than half of the time,More than half of the time
4,26-35,Female,Consulting,Data Scientist,North America,Onsite,Yes,Sometimes,Regularly,Regularly,...,Every day,Every day,Every day,A few times per week,A few times per week,Some of the time,At no time,Less than half of the time,Less than half of the time,Some of the time

In [ ]:
df.info()
df.isna().sum().sort_values(ascending=False).head(20)
df.describe(include="all").T.head(30)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Columns: 162 entries, Age to WB5
dtypes: float64(15), object(147)
memory usage: 6.2+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Age,4990,5,26-35,1381,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,4995,3,Female,2547,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Industry,4998,7,Consulting,778,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JobRole,4990,7,Software Engineer,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,4995,6,Asia,1354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WorkLocation,4994,3,Onsite,1929,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AccessMH,4996,2,No,2698,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wp1,4995,5,Sometimes,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wp2,4998,5,Often,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wp3,4994,5,Very often,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wp4,4995,5,Very often,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cogn1,4992,5,Often,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cogn2,4992,5,Regularly,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cogn3,4994,5,Very often,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cogn4,4993,5,Often,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emo1,4992,5,Often,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emo2,4990,5,Never,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emo3,4993,5,Never,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emo4,4997,5,Regularly,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emo5,4991,5,Regularly,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emo6,4996,5,Sometimes,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rolcon1,4998,5,Strongly agree,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rolcon2,4993,5,Strongly agree,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rolcon3,4999,5,Strongly agree,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rolcon4,4996,5,Neutral,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hassle1,4997,5,Neutral,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hassle2,4997,5,Disagree,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hassle3,4997,5,Strongly agree,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hassle4,4995,5,Agree,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hassle5,4993,5,Neutral,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#**MAPA DE VARIABLES**

La primera tarea antes de la limpieza será entender qué contiene cada una de las columnas (variables) que vienen con este dataset y ver la relevancia de cada columna dentro del tema de TFM.
Cada uno de los bloques (wp1–wp4, emo1–emo6, etc.) corresponde a una escala psicométrica donde todas sus variables miden lo mismo y tienen una escala de respuesta (ej. 1-5).

___
**Job demands:**

Las Demandas laborales suelen aumentar el riesgo de Burnout

*   Work Pressure: wp1,wp2,wp3,wp4 indican presión, carga, urgencia.
*   Demandas Cognitivas: cogn1, cogn2, cogn3, cogn4. Esfuerzo mental, concentración sostenida
*   Demandas sociales: soc1, soc2, soc3. exigencias sociales, trato con otros
*   Demandas emocionales: emo1, emo2, emo3, emo4, emo5, emo6. Desgaste emocional en el trabajo.

___
**Job Resources:**

Los recursos laborales suelen proteger contra el burnout.

*   Autonomy (JD–R): auto1, auto2, auto3. Miden el control sobre cómo se trabaja.
*   Feedback: feedb1, feedb2, feedb3. La retroalimentación suele dar claridad.
*   Coaching: coach1, coach2, coach3, coach4, coach5. Apoyo y guía directa.

___
**Effort–Reward Imbalance (ERI):**

(ERI): ERI1 a ERI10

Desbalance entre esfuerzo y recompensa. Es un Predictor fuerte de frustración crónica.
___
**Organizational Commitment**

OC1 a OC6

Apego emocional a la organización
___
**Social Support (multinivel)**

*   Supervisor Support: SS1, SS2, SS3
*   Organizational Support: OS1, OS2, OS3
*   Family Support: FS1, FS2, FS3
___
**Person–Environment Fit**

*   Person–Job Fit PJF1, PJF2, PJF3, PJF4
*   Person–Organization Fit POF1, POF2, POF3, POF4
*   Person–Supervisor Fit: PSF1 a PSF5
___
**Emotional Labor**

*  ELT1 a ELT4: Fingir emociones, regular expresiones
___
**Emotional Exhaustion** - **Burnout (core)**

*  ELT1 a ELT4: Núcleo de burnout
___
**Salud mental asociada**

*  Stress (DASS): S1 A S5
*  Anxiety: A1 a A5
*  Depression: D1 a D4
___
**Fatiga física y sueño**

Somatic Fatigue (GHQ): SF1 a SF9
___
**Bienestar positivo**
*  Well-being (WHO-5):WB1 a WB5
___
**Recursos y cognición**

* Conservation of Resources: CORS1 a CORS6
* Cognitive Appraisal: CAS1 a CAS12
___

#**LIMPIEZA DE DATASET**
1. INSPECCIÓN
2. NOMBRES DE COLUMNAS
NA'S
3. DUPLICADOS
4. TIPOS (CATEGORICAS VS NUMÉRICAS)
5. VALIDACIÓN DE RANGOS/VALORES RAROS
6. GUARDAR

##Inspección Inicial

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print(df.head(8))
print("\n--- INFO ---")
df.info()

     Age             Gender       Industry            JobRole         Region  \
0  26-35             Female     Consulting          Marketing         Africa
1    56+  Prefer not to say      Education  Software Engineer  South America
2  18-25             Female        Finance                 HR           Asia
3  36-45               Male     Healthcare           Designer         Africa
4  26-35             Female     Consulting     Data Scientist  North America
5  18-25             Female             IT              Sales  North America
6    56+             Female  Manufacturing           Designer  North America
7  46-55  Prefer not to say      Education  Software Engineer        Oceania

  WorkLocation AccessMH         wp1         wp2         wp3  ...  \
0       Remote      Yes   Sometimes       Often  Very often  ...
1       Onsite       No   Sometimes       Never   Sometimes  ...
2       Onsite       No       Often       Often   Sometimes  ...
3       Remote      Yes   Sometimes       Never   Sometimes  ...
4       Onsite      Yes   Sometimes   Regularly   Regularly  ...
5       Onsite      Yes   Sometimes   Regularly   Sometimes  ...
6       Onsite      Yes  Very often  Very often       Often  ...
7       Remote      Yes       Never   Sometimes   Regularly  ...

                    EE3                   EE4                   EE5  \
0             Every day  A few times per year           Once a week
1             Every day             Every day  A few times per week
2                 Never           Once a week                 Never
3           Once a week  A few times per week           Once a week
4             Every day             Every day             Every day
5          Once a month  A few times per year  A few times per year
6  A few times per week           Once a week          Once a month
7             Every day             Every day  A few times per week

                     EE6                   EE7                         WB1  \
0              Every day             Every day            Most of the time
1            Once a week  A few times per week            Most of the time
2  A few times per month                 Never  More than half of the time
3            Once a week             Every day  More than half of the time
4   A few times per week  A few times per week            Some of the time
5           Once a month                 Never  More than half of the time
6   A few times per week           Once a week            Some of the time
7   A few times per week             Every day            Most of the time

                          WB2                         WB3  \
0  Less than half of the time             All of the time
1            Most of the time  More than half of the time
2            Some of the time                  At no time
3  Less than half of the time            Most of the time
4                  At no time  Less than half of the time
5  More than half of the time            Some of the time
6            Most of the time            Most of the time
7            Most of the time  More than half of the time

                          WB4                         WB5
0            Most of the time            Most of the time
1  More than half of the time            Most of the time
2  Less than half of the time            Some of the time
3  More than half of the time  More than half of the time
4  Less than half of the time            Some of the time
5  More than half of the time  Less than half of the time
6  Less than half of the time  Less than half of the time
7  More than half of the time            Most of the time

[8 rows x 162 columns]

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Columns: 162 entries, Age to WB5
dtypes: float64(15), object(147)
memory usage: 6.2+ MB

### Descripción de variables numéricas

El análisis descriptivo de las variables numéricas muestra que algunas escalas del dataset ya se encuentran codificadas en formato numérico. En particular, los ítems correspondientes a la escala de Cognitive Appraisal (CAS) presentan valores entre 0 y 6, mientras que los ítems de la escala Conservation of Resources (CORS) presentan valores entre 1 y 5.

En ambos casos, los valores se distribuyen de forma equilibrada alrededor del punto medio de la escala, con medianas cercanas a 3 y sin presencia de valores fuera del rango esperado. Esto indica que las variables numéricas están correctamente codificadas y no requieren ajustes adicionales en esta etapa.

Estas variables podrán utilizarse directamente en los siguientes pasos del análisis, respetando el rango original de cada escala.

In [ ]:
print("\n--- DESCRIBE (numéricas) ---")
print(df.describe())

--- DESCRIBE (numéricas) ---
             CORS7        CORS8        CORS9         CAS1         CAS2  \
count  4995.000000  4997.000000  4991.000000  4995.000000  4994.000000
mean      2.999199     2.999600     3.000801     2.998799     2.999399
std       1.414496     1.414355     1.414497     2.000901     2.000450
min       1.000000     1.000000     1.000000     0.000000     0.000000
25%       2.000000     2.000000     2.000000     1.000000     1.000000
50%       3.000000     3.000000     3.000000     3.000000     3.000000
75%       4.000000     4.000000     4.000000     5.000000     5.000000
max       5.000000     5.000000     5.000000     6.000000     6.000000

             CAS3         CAS4         CAS5         CAS6         CAS7  \
count  4992.00000  4997.000000  4993.000000  4993.000000  4994.000000
mean      2.99980     3.001401     2.998398     3.001803     3.000000
std       2.00025     2.000450     2.000800     2.000750     2.000801
min       0.00000     0.000000     0.000000     0.000000     0.000000
25%       1.00000     1.000000     1.000000     1.000000     1.000000
50%       3.00000     3.000000     3.000000     3.000000     3.000000
75%       5.00000     5.000000     5.000000     5.000000     5.000000
max       6.00000     6.000000     6.000000     6.000000     6.000000

              CAS8       CAS9        CAS10        CAS11        CAS12
count  4993.000000  4996.0000  4995.000000  4993.000000  4994.000000
mean      3.000200     3.0000     2.998999     3.000601     2.998999
std       2.000451     2.0005     2.000751     2.000651     2.001051
min       0.000000     0.0000     0.000000     0.000000     0.000000
25%       1.000000     1.0000     1.000000     1.000000     1.000000
50%       3.000000     3.0000     3.000000     3.000000     3.000000
75%       5.000000     5.0000     5.000000     5.000000     5.000000
max       6.000000     6.0000     6.000000     6.000000     6.000000

### Exploración descriptiva de las variables

Se realizó un análisis descriptivo general de todas las variables del dataset utilizando estadísticas resumidas. En el caso de las variables categóricas y ordinales, como edad, género, industria y los ítems de las escalas psicométricas, se observan los valores más frecuentes y la cantidad de categorías distintas.

La mayoría de los ítems de las escalas presentan cinco opciones de respuesta (por ejemplo: Never, Sometimes, Often, Very often), lo cual es consistente con escalas tipo Likert comúnmente utilizadas en encuestas de salud laboral.

En esta etapa no se interpretan promedios ni desviaciones estándar para estos ítems, ya que actualmente se encuentran codificados como texto. Este análisis permite confirmar que los datos están completos, bien distribuidos y correctamente estructurados antes de proceder a su transformación a formato numérico.

In [ ]:
print("\n--- DESCRIBE (todas) ---")
print(df.describe(include="all").T.head(40))

--- DESCRIBE (todas) ---
             count unique                top  freq mean  std  min  25%  50%  \
Age           4990      5              26-35  1381  NaN  NaN  NaN  NaN  NaN
Gender        4995      3             Female  2547  NaN  NaN  NaN  NaN  NaN
Industry      4998      7         Consulting   778  NaN  NaN  NaN  NaN  NaN
JobRole       4990      7  Software Engineer   890  NaN  NaN  NaN  NaN  NaN
Region        4995      6               Asia  1354  NaN  NaN  NaN  NaN  NaN
WorkLocation  4994      3             Onsite  1929  NaN  NaN  NaN  NaN  NaN
AccessMH      4996      2                 No  2698  NaN  NaN  NaN  NaN  NaN
wp1           4995      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
wp2           4998      5              Often  1000  NaN  NaN  NaN  NaN  NaN
wp3           4994      5         Very often  1000  NaN  NaN  NaN  NaN  NaN
wp4           4995      5         Very often  1000  NaN  NaN  NaN  NaN  NaN
cogn1         4992      5              Often   999  NaN  NaN  NaN  NaN  NaN
cogn2         4992      5          Regularly   999  NaN  NaN  NaN  NaN  NaN
cogn3         4994      5         Very often  1000  NaN  NaN  NaN  NaN  NaN
cogn4         4993      5              Often  1000  NaN  NaN  NaN  NaN  NaN
emo1          4992      5              Often   999  NaN  NaN  NaN  NaN  NaN
emo2          4990      5              Never   999  NaN  NaN  NaN  NaN  NaN
emo3          4993      5              Never  1000  NaN  NaN  NaN  NaN  NaN
emo4          4997      5          Regularly  1000  NaN  NaN  NaN  NaN  NaN
emo5          4991      5          Regularly  1000  NaN  NaN  NaN  NaN  NaN
emo6          4996      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
rolcon1       4998      5     Strongly agree  1000  NaN  NaN  NaN  NaN  NaN
rolcon2       4993      5     Strongly agree  1000  NaN  NaN  NaN  NaN  NaN
rolcon3       4999      5     Strongly agree  1000  NaN  NaN  NaN  NaN  NaN
rolcon4       4996      5            Neutral  1000  NaN  NaN  NaN  NaN  NaN
hassle1       4997      5            Neutral  1000  NaN  NaN  NaN  NaN  NaN
hassle2       4997      5           Disagree  1000  NaN  NaN  NaN  NaN  NaN
hassle3       4997      5     Strongly agree  1000  NaN  NaN  NaN  NaN  NaN
hassle4       4995      5              Agree  1000  NaN  NaN  NaN  NaN  NaN
hassle5       4993      5            Neutral  1000  NaN  NaN  NaN  NaN  NaN
auto1         4991      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
auto2         4995      5              Never  1000  NaN  NaN  NaN  NaN  NaN
auto3         4997      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
soc1          4998      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
soc2          4993      5         Very often  1000  NaN  NaN  NaN  NaN  NaN
soc3          4992      5         Very often  1000  NaN  NaN  NaN  NaN  NaN
feedb1        4999      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
feedb2        4996      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
feedb3        4996      5          Sometimes  1000  NaN  NaN  NaN  NaN  NaN
coach1        4991      5          Regularly  1000  NaN  NaN  NaN  NaN  NaN

              75%  max
Age           NaN  NaN
Gender        NaN  NaN
Industry      NaN  NaN
JobRole       NaN  NaN
Region        NaN  NaN
WorkLocation  NaN  NaN
AccessMH      NaN  NaN
wp1           NaN  NaN
wp2           NaN  NaN
wp3           NaN  NaN
wp4           NaN  NaN
cogn1         NaN  NaN
cogn2         NaN  NaN
cogn3         NaN  NaN
cogn4         NaN  NaN
emo1          NaN  NaN
emo2          NaN  NaN
emo3          NaN  NaN
emo4          NaN  NaN
emo5          NaN  NaN
emo6          NaN  NaN
rolcon1       NaN  NaN
rolcon2       NaN  NaN
rolcon3       NaN  NaN
rolcon4       NaN  NaN
hassle1       NaN  NaN
hassle2       NaN  NaN
hassle3       NaN  NaN
hassle4       NaN  NaN
hassle5       NaN  NaN
auto1         NaN  NaN
auto2         NaN  NaN
auto3         NaN  NaN
soc1          NaN  NaN
soc2          NaN  NaN
soc3          NaN  NaN
feedb1        NaN  NaN
feedb2        NaN  NaN
feedb3        NaN  NaN
coach1        NaN  NaN

### Estructura general del dataset

El dataset final contiene un total de 162 columnas, que pueden agruparse en dos tipos principales: variables sociodemográficas y variables correspondientes a ítems de encuestas.

Las variables sociodemográficas incluyen información general de los participantes, como edad, género, industria, rol laboral, región, modalidad de trabajo y acceso a servicios de salud mental. Estas variables permiten describir el perfil de las personas encuestadas y comparar resultados entre distintos grupos.

El segundo grupo, que corresponde a la mayoría de las columnas, está formado por preguntas individuales de distintas escalas utilizadas para medir aspectos del entorno laboral y del bienestar de los trabajadores. Estas preguntas recogen información sobre carga de trabajo, demandas emocionales, apoyo social, estrés, bienestar y agotamiento emocional, entre otros factores.

Dado que estas preguntas están pensadas para medir un mismo concepto en conjunto, no se analizarán de forma individual. En su lugar, se agruparán para crear variables resumen por cada escala, lo que facilita el análisis y la interpretación de los resultados.

In [ ]:
import re

df_raw = df.copy() #creación de copia del datafrme df

def clean_col(c): #se define una función que se llama clean_col(C). Toma una columna c para hacer una serie de modificaciones.
    c = c.strip() # Elimina cualquier espacio inicial o final del nombre de la columna.
    c = c.replace(" ", "_").replace("-", "_").replace("/", "_") #Reemplaza espacios, guiones y barras diagonales por guiones bajos. Esto ayuda a crear nombres de columna más consistentes y accesibles (p. ej., Rol de trabajo se convierte en rol de trabajo)
    c = re.sub(r"[^0-9a-zA-Z_]+", "", c) #Esta es una sustitución de expresión regular. Busca cualquier carácter que NO sea un número (0-9), una letra mayúscula (A-Z), una letra minúscula (a-z) o un guion bajo (_), y lo reemplaza con una cadena vacía. Esto elimina eficazmente los caracteres especiales.
    c = re.sub(r"_+", "_", c) #Esto reemplaza cualquier secuencia de uno o más guiones bajos con un solo guion bajo, evitando que aparezcan varios guiones bajos juntos.
    return c.lower() #convierte todo el nombre de la columna limpiada a minúsculas.

df = df_raw.copy() #Restablece el df DataFrame a una copia nueva del df_raw original antes de aplicar la limpieza de la columna.
df.columns = [clean_col(c) for c in df.columns] #Esta línea aplica la función clean_col a cada nombre de columna del DataFrame. Itera sobre los nombres de columna existentes, los limpia con la función clean_col y, a continuación, asigna la lista de nombres nuevos y limpios a df.columns.

print(df.columns.tolist()[:40])
print("Total columnas:", len(df.columns))

['age', 'gender', 'industry', 'jobrole', 'region', 'worklocation', 'accessmh', 'wp1', 'wp2', 'wp3', 'wp4', 'cogn1', 'cogn2', 'cogn3', 'cogn4', 'emo1', 'emo2', 'emo3', 'emo4', 'emo5', 'emo6', 'rolcon1', 'rolcon2', 'rolcon3', 'rolcon4', 'hassle1', 'hassle2', 'hassle3', 'hassle4', 'hassle5', 'auto1', 'auto2', 'auto3', 'soc1', 'soc2', 'soc3', 'feedb1', 'feedb2', 'feedb3', 'coach1']
Total columnas: 162

### Tratamiento de valores faltantes (NA)

El análisis inicial de los valores faltantes muestra un total de 810 valores NA distribuidos entre distintas variables. Ninguna columna presenta una cantidad alta de datos faltantes, ya que el máximo observado es de 12 valores por variable.

Este comportamiento es común en encuestas largas, donde algunas personas pueden omitir ciertas preguntas de forma puntual. No se observa que los valores faltantes se concentren en una variable específica ni que sigan un patrón problemático.

Debido a que la cantidad de valores faltantes por columna es baja y las escalas están formadas por varias preguntas, no se eliminan filas ni se aplican métodos de imputación directa. En su lugar, los valores faltantes se manejarán al momento de crear variables resumen por escala, utilizando promedios que ignoran automáticamente los valores NA. De esta forma se conserva la mayor cantidad de información posible sin alterar los datos originales.

In [ ]:
na_total = df.isna().sum().sum() #df.isna(): Crea un DataFrame con valores booleanos, donde "True" indica un valor faltante (NaN) y "False" indica un valor válido.sum(): Aplicado a un DataFrame booleano, sum() cuenta los valores verdaderos (es decir, los valores faltantes) de cada columna.sum() (de nuevo): La segunda función sum() suma todos estos recuentos por columna, lo que proporciona el número total de valores faltantes en todo el DataFrame.
print("NA total:", na_total) #Esta línea simplemente imprime el número total calculado de valores faltantes.

na_by_col = df.isna().sum().sort_values(ascending=False) #df.isna().sum(): Como antes, esto calcula la cantidad de valores faltantes para cada columna.sort_values(ascending=False): Esto ordena la serie resultante de valores faltantes en orden descendente, de modo que las columnas con más valores faltantes aparezcan primero.
print("\nTop 20 columnas con más NA:")
print(na_by_col.head(20))

NA total: 810

Top 20 columnas con más NA:
eri9       12
age        10
emo2       10
sfq9       10
os2        10
jobrole    10
coach1      9
auto1       9
emo5        9
fs2         9
a4          9
cors9       9
s5          9
wb5         9
cogn1       8
emo1        8
cas3        8
cogn2       8
soc3        8
pjf2        8
dtype: int64

### Revisión de filas duplicadas

Se revisó el dataset para identificar posibles filas duplicadas que pudieran afectar los resultados del análisis. El conjunto de datos cuenta con un total de 5000 observaciones y, al comparar las filas completas, no se encontraron registros repetidos.

La eliminación de duplicados no generó cambios en el número de filas, lo que indica que cada observación corresponde a una respuesta única. Por esta razón, no fue necesario aplicar ningún ajuste adicional en este punto.

Este resultado permite continuar con el análisis con la confianza de que los datos no presentan problemas de duplicación.

In [ ]:
print("Filas totales:", len(df)) #Esta línea simplemente imprime el número total de filas presentes actualmente en su DataFrame df.
print("Filas únicas:", len(df.drop_duplicates())) #Esta línea crea primero un DataFrame temporal eliminando las filas duplicadas de df (sin modificar df aún). A continuación, calcula e imprime el número de filas en este DataFrame temporal, mostrando así cuántas filas únicas hay.

df = df.drop_duplicates().reset_index(drop=True) #Este es el paso crucial donde se eliminan las filas duplicadas.df.drop_duplicates(): Elimina las filas donde todos los valores de columna son idénticos a los de otra fila. Por defecto, conserva la primera ocurrencia de un conjunto duplicado.reset_index(drop=True): Tras eliminar filas, el índice del DataFrame original podría tener espacios vacíos. Este método restablece el índice a un índice entero predeterminado (0, 1, 2, ...). drop=True garantiza que el índice antiguo no se añada como una nueva columna al DataFrame.

print("Filas luego de drop_duplicates:", len(df)) #Finalmente, esta línea imprime el número total de filas en df después de que se hayan eliminado los duplicados, lo que confirma el nuevo tamaño de su DataFrame.

Filas totales: 5000
Filas únicas: 5000
Filas luego de drop_duplicates: 5000

### Identificación de ítems psicométricos

Como parte del proceso de limpieza y preparación de los datos, se identificaron de forma automática las columnas que corresponden a preguntas individuales de las escalas utilizadas en el cuestionario. Para ello, se aprovecharon los nombres de las variables, que siguen un patrón común (por ejemplo, wp1–wp4, emo1–emo6, ee1–ee7).

Mediante este procedimiento se detectaron un total de 129 ítems, lo cual coincide con la estructura del cuestionario y con la información descrita en la fuente del dataset.

La identificación de estos ítems es importante porque permite trabajar de forma ordenada con las escalas, aplicar el mismo tratamiento a todas las preguntas (como la conversión a valores numéricos o el manejo de valores faltantes) y preparar el dataset para la creación de variables resumen por escala.

Este enfoque ayuda a reducir errores y facilita que el análisis pueda ser replicado de forma consistente.

In [ ]:
# Este bloque de código está diseñado para identificar y procesar columnas que representan elementos de encuesta individuales (como 'wp1', 'cogn2', etc.) y convertir sus valores en un formato numérico.
item_pattern = re.compile(r"^(auto|wp|cogn|soc|emo|feedb|coach|eri|oc|ss|cs|os|fs|auton|comp|relat|pjf|pof|psf|elt|ee|s|a|d|sf|wb|cors|cas)\d+$")
#Esta línea define un patrón de expresión regular. Busca nombres de columna que comiencen con un prefijo específico (como "auto", "wp", "cogn", etc., que probablemente corresponda a diferentes escalas o categorías psicológicas de su "MAPA DE VARIABLES"), seguido de uno o más dígitos (\d+). Este patrón ayuda a identificar automáticamente todas las columnas que representan preguntas o elementos individuales de la encuesta.
item_cols = [c for c in df.columns if item_pattern.match(c)] #Esta línea utiliza una comprensión de lista para crear una lista llamada item_cols. Itera todos los nombres de columna en su DataFrame df y añade un nombre de columna a item_cols si coincide con la expresión regular item_pattern.
print("Cantidad de ítems detectados:", len(item_cols))
print("Ejemplos:", item_cols[:20])

# Este bucle recorre cada nombre de columna identificado en item_cols. Para cada una de estas columnas:
for c in item_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")
#Esta función intenta convertir los valores de esa columna a un tipo numérico. Si algún valor no se puede convertir (por ejemplo, si es texto o una cadena inesperada), errors="coerce" indica a Pandas que reemplace ese valor no convertible con NaN (No es un número), convirtiendo las entradas no válidas en valores faltantes.

Cantidad de ítems detectados: 129
Ejemplos: ['wp1', 'wp2', 'wp3', 'wp4', 'cogn1', 'cogn2', 'cogn3', 'cogn4', 'emo1', 'emo2', 'emo3', 'emo4', 'emo5', 'emo6', 'auto1', 'auto2', 'auto3', 'soc1', 'soc2', 'soc3']

### Validación de rangos de respuesta

Durante la revisión de los rangos de las variables numéricas se observó que los ítems de la escala de Cognitive Appraisal (CAS1–CAS12) toman valores entre 0 y 6.

Esto no corresponde a un error en los datos, sino a la forma en que fue definida originalmente esta escala. A diferencia de otras escalas tipo Likert que comienzan en 1, en este caso el valor 0 es una opción válida de respuesta y puede representar la ausencia del aspecto evaluado.

El hecho de que todos los ítems de esta escala compartan el mismo rango de valores indica que los datos son consistentes y están correctamente codificados. Por esta razón, no se aplican transformaciones ni recodificaciones sobre estas variables y se mantiene su escala original para los análisis posteriores.

In [ ]:
#Este bloque de código verifica el rango numérico de las columnas de elementos identificadas
if item_cols: #Esto garantiza que las siguientes operaciones solo se ejecuten si se detectan columnas de elementos (es decir, si la lista item_cols no está vacía).
    mins = df[item_cols].min(numeric_only=True)
    maxs = df[item_cols].max(numeric_only=True)
#Estas líneas calculan los valores mínimo y máximo de cada columna de la lista item_cols. numeric_only=True garantiza que solo se consideren las columnas numéricas.
    print("Mínimo global (ítems):", mins.min())
    print("Máximo global (ítems):", maxs.max())
#Estas líneas imprimen los valores mínimo y máximo absolutos encontrados en todas las columnas de elementos. Esto proporciona una idea general del rango total de respuestas en estos elementos de la encuesta.
    # Se inicializa una lista vacía para almacenar información sobre las columnas que podrían contener valores fuera de un rango esperado específico.
    out_of_range = [] #Este bucle itera sobre cada columna del elemento.
    for c in item_cols:
        col_min = df[c].min()
        col_max = df[c].max()
        #Dentro del bucle, encuentra los valores mínimo y máximo específicamente para la columna actual c.
        if pd.notna(col_min) and pd.notna(col_max): #Esta condición comprueba si los valores mínimo y máximo de la columna no son NaN. Esto es importante porque una columna con todos los valores NaN resultaría en NaN para min() y max(), que no se pueden comparar numéricamente.
            if col_min < 1 or col_max > 7: #Si col_min < 1 o col_max > 7: Si el valor mínimo de la columna es menor que 1 o su valor máximo es mayor que 7, significa que la columna contiene valores fuera del rango esperado de 1 a 7 (lo cual suele ser común en las escalas Likert). La condición col_max > 7 es una buena práctica para garantizar que todos los valores estén dentro de los límites esperados.
                out_of_range.append((c, col_min, col_max)) #Si una columna está fuera de rango, su nombre y sus valores mínimo y máximo reales se añaden a la lista "out_of_range".

    print("\nColumnas fuera de rango 1..7 (si aplica):", len(out_of_range))
    print(out_of_range[:20]) #imprimen el recuento de columnas fuera del rango 1-7 y muestran las primeras 20 columnas junto con sus respectivos valores mínimo/máximo.

Mínimo global (ítems): 0.0
Máximo global (ítems): 6.0

Columnas fuera de rango 1..7 (si aplica): 12
[('cas1', 0.0, 6.0), ('cas2', 0.0, 6.0), ('cas3', 0.0, 6.0), ('cas4', 0.0, 6.0), ('cas5', 0.0, 6.0), ('cas6', 0.0, 6.0), ('cas7', 0.0, 6.0), ('cas8', 0.0, 6.0), ('cas9', 0.0, 6.0), ('cas10', 0.0, 6.0), ('cas11', 0.0, 6.0), ('cas12', 0.0, 6.0)]

## Construcción de variables agregadas por escala

El dataset contiene una gran cantidad de columnas que corresponden a preguntas individuales de distintos cuestionarios. Muchas de estas preguntas forman parte de una misma escala y están diseñadas para medir un mismo aspecto, como carga laboral, estrés, apoyo social o agotamiento emocional.

Analizar estas preguntas una por una no resulta práctico ni fácil de interpretar. Además, estas preguntas no fueron pensadas para ser analizadas de forma individual, sino como un conjunto que representa una dimensión más amplia.

### Conversión de respuestas tipo Likert a valores numéricos

Antes de poder construir variables agregadas, es necesario convertir las respuestas que actualmente están en formato de texto (por ejemplo, *Never*, *Sometimes*, *Often*, *Very often* o *Strongly agree*) a valores numéricos.

Esta conversión respeta el orden natural de las respuestas. Por ejemplo, respuestas que indican mayor frecuencia o mayor acuerdo reciben valores numéricos más altos, mientras que respuestas que indican menor frecuencia o desacuerdo reciben valores más bajos. Este paso no modifica el significado de los datos, sino que permite trabajar con ellos de forma cuantitativa.

Una vez realizada esta conversión, cada pregunta individual puede representarse mediante un número, lo que permite realizar cálculos como promedios y comparaciones entre personas.

### Construcción de variables resumen por escala

Después de convertir las respuestas a valores numéricos, se procede a construir variables agregadas por escala. Esto se realiza calculando el promedio de las preguntas que pertenecen a una misma dimensión.

Por ejemplo, si una escala de carga laboral está compuesta por varias preguntas, el promedio de esas respuestas representa el nivel general de carga laboral reportado por cada persona. De esta manera, en lugar de trabajar con múltiples columnas separadas, se obtiene una única variable que resume la información principal de la escala.

Este enfoque permite:
- reducir la cantidad de variables del dataset,
- facilitar la interpretación de los resultados,
- y manejar de forma natural los valores faltantes, ya que los promedios se calculan ignorando los valores NA cuando estos son pocos.

### Relación con el análisis de burnout

El objetivo principal de este trabajo es identificar patrones asociados al burnout. Para ello, resulta fundamental contar con variables que representen claramente conceptos como agotamiento emocional, estrés, demandas laborales y apoyo social.

Las variables agregadas por escala permiten comparar grupos de personas, por ejemplo:
- personas con altos niveles de agotamiento emocional frente a aquellas con niveles bajos,
- o analizar cómo se comportan otras variables (carga laboral, apoyo, bienestar) en personas que reportan burnout.

De esta forma, la construcción de variables agregadas es un paso clave para identificar patrones y relaciones que ayuden a comprender qué factores están más asociados al riesgo de burnout en el entorno laboral.


Para evitar modificar el dataset original, todas las transformaciones posteriores se realizarán sobre copias del conjunto de datos. De esta forma, se preserva una versión base de los datos y se garantiza que cada etapa del proceso pueda revisarse o reproducirse de manera independiente.

A partir del dataset original se crearán versiones simplificadas que permitirán convertir las respuestas en texto a valores numéricos y, posteriormente, construir variables agregadas por escala.

In [ ]:
import pandas as pd
import numpy as np
df_original = df.copy(deep=True)   # lo guardamos

###Crear una copia para convertir texto a números

In [ ]:
df_numeric = df_original.copy(deep=True)

###Definir mapeos Likert (frecuencia y acuerdo)

In [ ]:
# Frecuencia (ej: Never -> Very often)
FREQ_MAP = {
    "never": 1,
    "sometimes": 2,
    "regularly": 3,
    "often": 4,
    "very often": 5,
}

# Acuerdo (ej: Strongly disagree -> Strongly agree)
AGREE_MAP = {
    "strongly disagree": 1,
    "disagree": 2,
    "neutral": 3,
    "agree": 4,
    "strongly agree": 5,
}

###Convertir columnas de texto

In [ ]:
def try_map_likert_series(s: pd.Series) -> pd.Series:
    """Intenta convertir una columna tipo Likert (texto) a números.
       Si no calza bien, devuelve la columna original."""
    if not pd.api.types.is_object_dtype(s) and not pd.api.types.is_string_dtype(s):
        return s  # no es texto

    # Normalizar texto
    s_norm = s.astype(str).str.strip().str.lower()

    # Si hay strings como "nan", los volvemos NaN reales
    s_norm = s_norm.replace({"nan": np.nan, "none": np.nan, "": np.nan})

    # Valores únicos (sin NaN)
    uniq = set(s_norm.dropna().unique().tolist())
    if len(uniq) == 0:
        return s  # columna vacía

    # Decide si parece frecuencia o acuerdo
    freq_keys = set(FREQ_MAP.keys())
    agree_keys = set(AGREE_MAP.keys())

    # Si TODOS los valores únicos están dentro del mapa -> convertir
    if uniq.issubset(freq_keys):
        return s_norm.map(FREQ_MAP)
    if uniq.issubset(agree_keys):
        return s_norm.map(AGREE_MAP)
        # Si no calza perfecto, no tocamos
    return s

###Aplicar la conversión a todas las columnas

In [ ]:
converted_cols = []
skipped_cols = []

for c in df_numeric.columns:
    before = df_numeric[c]
    after = try_map_likert_series(before)

    # Detectar si cambió a numérico
    if not after.equals(before) and pd.api.types.is_numeric_dtype(after):
        df_numeric[c] = after
        converted_cols.append(c)
    else:
        skipped_cols.append(c)

print("Columnas convertidas a numérico (texto→número):", len(converted_cols))
print("Ejemplos:", converted_cols[:25])

Columnas convertidas a numérico (texto→número): 9
Ejemplos: ['rolcon1', 'rolcon2', 'rolcon3', 'rolcon4', 'hassle1', 'hassle2', 'hassle3', 'hassle4', 'hassle5']

###Verificación

In [ ]:
print("Tipos de datos (top 30):")
print(df_numeric.dtypes.head(30))

# ¿Cuántas columnas numéricas tenemos ahora?
num_cols = df_numeric.select_dtypes(include="number").columns
print("\nColumnas numéricas totales:", len(num_cols))

# NA total luego de convertir (no debería explotar)
print("\nNA total en df_numeric:", df_numeric.isna().sum().sum())

Tipos de datos (top 30):
age              object
gender           object
industry         object
jobrole          object
region           object
worklocation     object
accessmh         object
wp1             float64
wp2             float64
wp3             float64
wp4             float64
cogn1           float64
cogn2           float64
cogn3           float64
cogn4           float64
emo1            float64
emo2            float64
emo3            float64
emo4            float64
emo5            float64
emo6            float64
rolcon1         float64
rolcon2         float64
rolcon3         float64
rolcon4         float64
hassle1         float64
hassle2         float64
hassle3         float64
hassle4         float64
hassle5         float64
dtype: object

Columnas numéricas totales: 138

NA total en df_numeric: 570251

###Se guarda el nuevo dataframe numérico

In [ ]:
df_numeric.to_csv("dataset_numeric.csv", index=False)
print("✅ Guardado: dataset_numeric.csv")

✅ Guardado: dataset_numeric.csv

In [ ]:
[c for c in df_numeric.columns if c.lower().startswith("ee")]

['ee1', 'ee2', 'ee3', 'ee4', 'ee5', 'ee6', 'ee7']

In [ ]:
# Copia de trabajo (NO modifica el dataset original)
df_scales = df_numeric.copy()

print(df_scales.shape)

(5000, 162)

In [ ]:
EE_cols = ['ee1', 'ee2', 'ee3', 'ee4', 'ee5', 'ee6', 'ee7']
df_scales[EE_cols] = df_scales[EE_cols].apply(
    pd.to_numeric, errors='coerce'
)

df_scales['EE_mean'] = df_scales[EE_cols].mean(axis=1, skipna=True)

In [ ]:
df_scales.shape, df_scales.columns[:162]

((5000, 162),
 Index(['age', 'gender', 'industry', 'jobrole', 'region', 'worklocation',
        'accessmh', 'wp1', 'wp2', 'wp3',
        ...
        'ee3', 'ee4', 'ee5', 'ee6', 'ee7', 'wb1', 'wb2', 'wb3', 'wb4', 'wb5'],
       dtype='object', length=162))

In [ ]:
[c for c in df_scales.columns if "ee" in str(c)]

['feedb1', 'feedb2', 'feedb3', 'ee1', 'ee2', 'ee3', 'ee4', 'ee5', 'ee6', 'ee7']

In [ ]:
print("EE en df_numeric:", [c for c in df_numeric.columns if "ee" in str(c)])
print("EE en df_original:", [c for c in df_original.columns if "ee" in str(c)])

EE en df_numeric: ['feedb1', 'feedb2', 'feedb3', 'ee1', 'ee2', 'ee3', 'ee4', 'ee5', 'ee6', 'ee7']
EE en df_original: ['feedb1', 'feedb2', 'feedb3', 'ee1', 'ee2', 'ee3', 'ee4', 'ee5', 'ee6', 'ee7']

In [ ]:
df_scales[EE_cols].dtypes

ee1    float64
ee2    float64
ee3    float64
ee4    float64
ee5    float64
ee6    float64
ee7    float64
dtype: object

In [ ]:
wp_cols = ['wp1','wp2','wp3','wp4']
df_scales[wp_cols] = df_scales[wp_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
df_scales['wp_mean'] = df_scales[wp_cols].mean(axis=1, skipna=True)

In [ ]:
df_scales[['wp_mean']].head()

   wp_mean
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

In [ ]:
cogn_cols = ['cogn1','cogn2','cogn3','cogn4']
df_scales[cogn_cols] = df_scales[cogn_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
df_scales['cogn_mean'] = df_scales[cogn_cols].mean(axis=1, skipna=True)

In [ ]:
df_scales[['cogn_mean']].head()

   cogn_mean
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN

In [ ]:
emo_cols = ['emo1','emo2','emo3','emo4','emo5','emo6']
df_scales[emo_cols] = df_scales[emo_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
df_scales['emo_mean'] = df_scales[emo_cols].mean(axis=1, skipna=True)

In [ ]:
df_scales[['emo_mean']].head()

   emo_mean
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

In [ ]:
df_scales[['EE_mean','wp_mean','cogn_mean','emo_mean']].describe()

       EE_mean  wp_mean  cogn_mean  emo_mean
count      0.0      0.0        0.0       0.0
mean       NaN      NaN        NaN       NaN
std        NaN      NaN        NaN       NaN
min        NaN      NaN        NaN       NaN
25%        NaN      NaN        NaN       NaN
50%        NaN      NaN        NaN       NaN
75%        NaN      NaN        NaN       NaN
max        NaN      NaN        NaN       NaN

In [ ]:
df_scales['EE1'].value_counts().head()

KeyError: 'EE1'

In [ ]:
df_scales['EE_mean'] = df_scales[ee_cols].mean(axis=1, skipna=True)

df_scales['EE_mean'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: EE_mean, dtype: float64